### ISSUE TITLE
Spec and write tests for new PDRE API changes

### ISSUE THREAD

**Issue by lamafab** [w3f/polkadot-spec#102]
As discussed, what has to be done:
- [x] - Extend the spec for the new, reworked PDRE API changes.
- [x] - Write the tests for those APIs.
  - Separate code bases between the new and "legacy" PDRE (since the legacy PDRE has to point to a specific Substrate commit).

Changes occur on the `pdre-new-apis` branch.

**Comment by lamafab** [comment]
PR here -> #119

**Comment by drskalman** [comment]
Could you comment the part of the implementation which is remaining here thta we mentioned in the meeting just to update the issue?

**Comment by lamafab** [comment]
Two things must be done:
- [x] - Wait for upstream fixes for building Kagome.
- [x] - Rename "Runtime Environment" to "Host" (see #122)
