### ISSUE TITLE
Convert glossary to latex and then import into texmacs

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#105]
The glossary is in mark down and can be found here right now here
   https://github.com/lamafab/polkadot-spec-glossary

**Comment by FlorianFranzen** [comment]
As discussed in strategy, @drskalman will do the initial work of including the glossary as glossary and index items.

**Comment by drskalman** [comment]
Chapter 01 is done in 4b5cf87b of #447

**Comment by drskalman** [comment]
Chapter 02 done in acf683d7
