### ISSUE TITLE
Can not compile and link to Kagome scale implementation

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#11]
I'm trying to add a command line helper which  links to and tests kagome scale implementation. See here:
[https://github.com/w3f/polkadot-re-tests/blob/f--kagome-scale/test/testers/cpp-tester/CMakeLists.txt#L1](url)

However, I get these errors when I try to compile. Could you resolve it?

```
-- Boost version: 1.69.0
-- Configuring done
-- Generating done
-- Build files have been written to: ./polkadot-re-tests/build
[  0%] Built target git_submodule_init
[ 10%] Building CXX object implementations/cpp/kagome/core/scale/CMakeFiles/scale.dir/basic_stream.cpp.o
In file included from ./polkadot-re-tests/implementations/cpp/kagome/core/common/buffer.hpp:13,
                 from ./polkadot-re-tests/implementations/cpp/kagome/core/scale/basic_stream.hpp:9,
                 from ./polkadot-re-tests/implementations/cpp/kagome/core/scale/basic_stream.cpp:6:
./polkadot-re-tests/implementations/cpp/kagome/core/common/result.hpp:46:21: error: expected constructor, destructor, or type conversion before ‘;’ token
   Value(T)->Value<T>;
                     ^
...

**Comment by Warchant** [comment]
@kamilsa, we need to make sure that kagome can be included as a submodule. I added task https://soramitsu.atlassian.net/browse/PRE-138

**Comment by FlorianFranzen** [comment]
Seems to be fixed. Kagome is included as a submodule The cpp-tester/kagome_tester builds against it fine. Scale test fixture executes successful.
