### ISSUE TITLE
Spec Force Change in Auth set

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#116]
The Spec team was told that Force Changes to Authority set is mainly theoretical and matter of last resort and are not 
  going to be used as such they are currently specced as reserved messages. 

  However in the research meeting of Jan 13 It was announced that actually we are going to use them on regular basis and therefore they need to be spec.

  Therefore we need to add the ForceChange message and their description to the Runtime-to-Consensus Engine section.

**Comment by lamafab** [comment]
PR here -> #120

**Comment by drskalman** [comment]
![image](https://user-images.githubusercontent.com/35698397/74647613-f7cb9c00-5149-11ea-9325-7039da7aca62.png)
