### ISSUE TITLE
Integrate the integration tests from DevOps to

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#117]
We need to get Polkadot deployer that devops has prepared and intgerate it as intgeration test. Which eventually runs 
   other implementations of Polkadot node beside Rust and run some connectivity tests between them.

**Comment by FlorianFranzen** [comment]
Is that still something we want to do? I feel like testing deployment tools are outside the scope of spec and for the simple integrations tests it is enough to just build each host from source for now. 

Once we get to multi-node tests we might utilize the devop code to implement our tests, but even then we might not use the `deployer` directly buy only through `polkadot-labs`. This is why I would close the issue for now.

**Comment by drskalman** [comment]
That is basically about using `polkadot-labs` for `multi-node` tests. Why do you close this issue and then open another one?

**Comment by FlorianFranzen** [comment]
All future work will continue in #194.
