### ISSUE TITLE
Julia tester code clean up

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#125]
Current julia tester basically repeat the test code for each test and each subtest. The tester structure should change to avoid such repetitions.

**Comment by drskalman** [comment]
Basically done, waiting for Kagome build issue to be resolved to be merged.

**Comment by FlorianFranzen** [comment]
Did this get merged yet? Do the patches from #154 help with your build issue?

**Comment by lamafab** [comment]
@FlorianFranzen This issue is basically part of #157. Once that is merged, this issue can be closed.
