### ISSUE TITLE
Spec Storage changes trie

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#129]
Storage change trie root is part of digest 
   https://github.com/paritytech/substrate/blob/master/test-utils/runtime/src/system.rs#L217
   
   And we need to spec how it is generated.

**Comment by lamafab** [comment]
=> #142

**Comment by drskalman** [comment]
To be reviewed by @FlorianFranzen.

**Comment by drskalman** [comment]
@FlorianFranzen adds his review and then reassign to @sklaman for final review.

**Comment by FlorianFranzen** [comment]
We went through multiple rounds of review and discussion so far in #142. @lamafab is in the progress to distill a final version with some of the changes still outstanding from my final review in #160. I assume @lamafab will submit for final review as soon as he is done.

**Comment by drskalman** [comment]
back for @drskalman for re-review.

**Comment by drskalman** [comment]
Back to @drskalman

**Comment by drskalman** [comment]
@drskalman did a prelimenary review, we need more example to be more comprehensible. There is also lots of changes to the API so it is worth to put the issue on hold till the dust settled.

**Comment by drskalman** [comment]
We will discuss with @lamafab if to merge this, otherwise it is ready to be merged.
