### ISSUE TITLE
Spec GRANDPA catch up procedure

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#134]
This include speccing:
- [ ] The condition which merits sending a catchup request.
- [ ] Which a cachup request desreves a response.
- [ ] catchup request message.
- [ ] catchup response message.
- [ ] Algorithm to process a catch up request and generate a response.
- [ ] Algorithm to process a catch up response and how to update the state accordingly.

**Comment by drskalman** [comment]
- [X] catchup request message. 37f645b65dc51f18fe8d8b201ee45e6b85146d3c
- [X] catchup response message. df131fb7d145c360c3c0538d30ecee2cb0e33419

**Comment by drskalman** [comment]
- [X] The condition which merits sending a catchup request. : ca073f2 When to send catch-up request specced in Polkadot Host.

**Comment by drskalman** [comment]
@lamafab will review the pull request.

**Comment by lamafab** [comment]
CatchUp message review is here -> https://github.com/w3f/polkadot-spec/issues/132#issuecomment-617881385

**Comment by drskalman** [comment]
@drskalman will merge to master and then send to @AlistairStewart for review.
