### ISSUE TITLE
Spec all tasks that a node needs to accomplish to join Polkadot properly in one chapte

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#135]
There are various steps that a node needs to take to bootstrap to Polkadot network. There are some nework related tasks:
- [x] Discovery.
- [x] Befriending peers at libp2p level.
- ...
But also there are different tasks at Polkadot level
- [ ] confirming network/genesis hash.
- [x] Exchanging status messages.
- [x] Importing blocks.
- [ ] updating Authority set.
- [ ] Updating the finalization rounds
- [ ] Last finalized block.
....
It seems that it merits its own chapter where possibly refers to Algorithms from other chapters.

**Comment by FlorianFranzen** [comment]
We should reevaluate this list once #333 is merged.

**Comment by FlorianFranzen** [comment]
@drskalman will start an introduction/foreword to the spec that points to all relevant chapters with a rough overview and a list of todos (see above).

**Comment by drskalman** [comment]
We started #389 . @lamafab will finish it up and fill in the details.
