### ISSUE TITLE
Make task for Kagome audit

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#136]
We need to make a check list for the items that we need to verify in Kagome implementation.

**Comment by drskalman** [comment]
Initial list from the meeting of Thu Feb 27 2020:
 - [x] Make Kagome.
 - [x] Fire a node and it should be able to work on itself.
 - [x] So it should be able to load genesis state.
 - [ ] It should be able to set storage. (check the trie hash compare with substrate base polkadot).
 - [ ] Make progressively more complicated genesis sate.
 - [ ] Import a block. (this means that we should be able to make valid blocks based on genesis.)
 - [ ] The blocks should become more increasingly more complicated in sense of using of more runtime modules and Host APIs.
 - [ ] transaction submission.
 - [ ] All transaction pool stuff: prerequist, .... priority.
 - [ ] submit multiple different transaction with different dependacy etc.
 - [ ] Babe production:
  - [ ] Tracking authority set.
  - [ ] Initiate block 
  - [ ] generetates inherents 
  - [ ] and apply them. 
  - [ ] Choosing from transaction pool.
  - [ ] apply transactions
  - [ ] finalize block.
  - [ ] import the finalized block.
  - [ ] Gossip the block.

 - Network.
   TBD
       
 - Grandpa.
   TBD

**Comment by FlorianFranzen** [comment]
Some initial work is being done [here](https://gitlab.w3f.tech/grants/soramitsu), the current progress is tracked in the issue section. Apart from the list here, David also posted a [checklist in the repository](https://gitlab.w3f.tech/grants/soramitsu/-/blob/master/evaluation/initial-checklist.md).
