### ISSUE TITLE
Make tasks for availability and Validity Speccing

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#141]
@drskalman should read through the AnV document and break the protocol in several sub protocol and process them according to the process agreed in the meeting.

Process to deal with each protocol task is:
- Read the definition of the protocol in the research paper.
- Look for the code of the protocol in the pool request
- If found:
  - write a spec algorithm which take both the paper and the code into account.
  - Share the spec with AnV research and seek feedback.
  - Incorporate reviews and  share it back with dev.

- If not found:
  - Ask dev about possible implementation.
  - If non, write the spec from the research paper.

**Comment by burdges** [comment]
Apologies on being behind in merging the new changes back in.  I just really need to get the ring-vrf working asap.

**Comment by drskalman** [comment]
Related tickets: #146, #147, #148, #149, #150
