### ISSUE TITLE
Run Pallet benchmarks on different machines (VPS, etc.), report results to Parity

### ISSUE THREAD

**Issue by lamafab** [w3f/polkadot-spec#143]
Also;
- Scrub Substrate and update script with newest benchmarks, create PR.

**Comment by lamafab** [comment]
-> Waiting for https://github.com/paritytech/substrate/pull/5269

**Comment by lamafab** [comment]
Tests have been run on multiple machines and submitted to Parity. Also, I've made an Ansible script which makes executing benchmarks on remote machines much easier: https://github.com/shawntabrizi/substrate-graph-benchmarks/pull/2

This issue will be "work-in-progres" for a while, since new benchmarks will be added over time.

**Comment by drskalman** [comment]
- It only needs small adjustment.
- But it is an ongoing issue, which need to be updated, which at that point it can be taken off the Spec Board.

**Comment by lamafab** [comment]
Currently waiting for this: https://github.com/w3f/infrastructure/issues/133

**Comment by drskalman** [comment]
This is waiting for Devops team work.
