### ISSUE TITLE
Compare Babe Spec and Babe Implementation with Babe paper

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#144]
We need to compare babe implementation with babe spec and submit any discrepency to research-security-issues repo.

**Comment by drskalman** [comment]
Currently the more important part is the relative time protocol part of it because the slot selection part is going to be replaced by the SASS.

Babe research write up can be found here:

https://github.com/w3f/research/blob/master/docs/polkadot/BABE/Babe.md
But check with @hndnklnc for the latest write up.

**Comment by hndnklnc** [comment]
It is the latest writeup. If you have any questions, you can ask me.

**Comment by FlorianFranzen** [comment]
I am updating our spec to the latest write up right now. Current progress it tracked in w3f/research-internal#110

**Comment by drskalman** [comment]
@FlorianFranzen is going to the current host spec according to the latest babe spec with recent constant hardcoded.

**Comment by drskalman** [comment]
The Babe spec is being followed up in issue #168 
And the descrepancy between the rust implementation and the Spec is discussed in https://github.com/w3f/research-security-issues/issues/7

**Comment by burdges** [comment]
I found the randomness was not being recycled correctly, to which wei proposed a fix in https://github.com/paritytech/substrate/pull/5788 although they'll compare with another fix approach. 

We should figure out if the randomness recycles from one epoch waits long enough before being used in another epoch.

**Comment by burdges** [comment]
Fix merged https://github.com/paritytech/substrate/pull/5876

I donno if they merged the whole migration machinery yet though.
