### ISSUE TITLE
Spec One-shot delay assignment for apporval checkers

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#147]
This is the first assignment protocol to be implemented and is descirbed in 
   https://github.com/w3f/research/blob/master/docs/papers/AnV/AnV-3-approval.tex and to be specced in 
   https://github.com/w3f/polkadot-spec/blob/spec-rt-anv-vrf-gen-and-announcement/runtime-spec/availability_and_validity.tex

**Comment by lamafab** [comment]
Closing on behalf of #468
