### ISSUE TITLE
Spec approval check procedure

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#149]
All the details which approval checker validators need to check before they are able to claim validity (or otherwise). 
   https://github.com/w3f/research/blob/master/docs/papers/AnV/AnV-3-approval.tex and to be specced in 
   https://github.com/w3f/polkadot-spec/blob/spec-rt-anv-vrf-gen-and-announcement/runtime-spec/availability_and_validity.tex

**Comment by lamafab** [comment]
Closing on behalf of #468
