### ISSUE TITLE
Spec the network message for validity or invalidity of a block during approval check phase

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#150]
When a approval checker decides that a block is valid or not it needs to gossip this message to the network
   https://github.com/w3f/research/blob/master/docs/papers/AnV/AnV-3-approval.tex
   https://github.com/w3f/polkadot-spec/blob/spec-rt-anv-vrf-gen-and-announcement/runtime-spec/availability_and_validity.tex

**Comment by lamafab** [comment]
Closing on behalf of #468
