### ISSUE TITLE
Update Polkadot Runtime Environment to Polkadot Host

### ISSUE THREAD

**Issue by Swader** [w3f/polkadot-spec#151]
There are many references and file and folder names referencing PRE instead of the new name - Polkadot Host. This should be updated asap.

**Comment by FlorianFranzen** [comment]
We have been updating code and documentation as far as possible. It is still present in the name of some of the test names (i.e. PD__RE__) or README links (#155). We will update them as we go. Let us know if you find anything else and I will reopen the issue.
