### ISSUE TITLE
Define last completed round in contrast to last finalized round

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#161]
In GRANDPA and specifically in the code there is three different concepts of rounds:

 - completable round
 - completed round 
 - finalized round 

We need to make the difference of these three concepts clear in the spec.

**Comment by drskalman** [comment]
1. completable round is the same as the spec definition of it in Definition 6.3.
2. We don't have notation of completed round, the node just need to complete algorithm 6.9 which basically means the round is completed.
3. We don't call a round to be finalized neither they code does, we both only call a block to be finalized.

**Comment by FlorianFranzen** [comment]
@drskalman There is still a todo for this in section 6.4.1.2 (Processing catch-up requests) of the host-spec in place of a definition of "Last-Completed-Round", Could you please take a look at this and see what needs to be done?

**Comment by drskalman** [comment]
Checked @FlorianFranzen's comment. replaced the todo and updated relevant algorithms: 8cc23e11. Needs @AlistairStewart review.

**Comment by drskalman** [comment]
I sought @AlistairStewart oral review. Everything is correct. Except, rejoining should happen in the same round that the node has left. I'll update the spec and the pull request.

**Comment by drskalman** [comment]
Following my talk to @AlistairStewart, if you disconnect and connect again then you should keep with the last round
    you had before nothing changes. If you are starting a fresh authority set then last round is 0.

    This is reflected in 44a6b26c

    The rest of changes was approved verbally.
