### ISSUE TITLE
Kagome code review

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#172]
We are going to follow the Host Spec and assign each chapter of the spec to a reviewer to review Kagome's code corresponding to that chapter. I made some initial unconsensual assignments but we can change it if doesn't make sense.
- [x] State Spec @drskalman
- [x] State Transition. @lamafab
- [x] Consensus Babe. @FlorianFranzen
- [x] Consensus Grandpa. @drskalman
- [x] Crypto algorithms. @drskalman
- [x] SCALE @lamafab
- [x]  Network Messages. @FlorianFranzen 
- [x] Importing Genesis State. @FlorianFranzen
- [x] Host API @lamafab

**Comment by drskalman** [comment]
If you object to the assignement please express comment it here. Otherwise make an issue for each assignment and assign it to yourself and start working on it :-)

**Comment by drskalman** [comment]
@drskalman: Grandpa #177.
@FlorianFranzen makes a ticket for Babe. (Done in #186)
@lamafab wll wok on State Transition.

**Comment by lamafab** [comment]
Current progress on State Transition, SCALE codec and Host API.

--> https://gitlab.w3f.tech/grants/soramitsu/-/issues/9

**Comment by drskalman** [comment]
- @lamafab puts it on the gitlab the result on the ticket and put the link in this ticket.

**Comment by drskalman** [comment]
- main focus of @FlorianFranzen 
- grandpa review is going to finish pretty soon.

**Comment by drskalman** [comment]
- Fabio taken over Grandpa messages and Spec Trie.
- Florian finishing network messages. Genesis seems fine. 
- we'll put raw reports in gitlab/grants/soramitsu/evaluation/

**Comment by drskalman** [comment]
talk to @Noc2 to clarify the priority of this over gossamer review? It seems is more of priority.

**Comment by Noc2** [comment]
Sorry for the late reply. It would be nice if someone could start looking into Gossamer this week, since officially BABE and GRANPA are ready for review according to Chainsafe.

**Comment by drskalman** [comment]
@lamafab will review  the Kagome state spec.

**Comment by drskalman** [comment]
- @drskalman done with Grandpa.
- @FlorianFranzen done wth Genesis.
- @FlorianFranzen  works on the network.
- @lamafab check if the overlay and state machine get updated correctly while changing forks.

**Comment by FlorianFranzen** [comment]
@drskalman Could you please update your remaining issues on the [gitlab issue tracker](https://gitlab.w3f.tech/grants/soramitsu/-/issues?scope=all&utf8=%E2%9C%93&state=opened&author_username=syed)?

@FlorianFranzen will take a brief look at the networking messages.

**Comment by drskalman** [comment]
I made issue #396 to track the reviewing the Kagome is improvements so that doesn't block closing this issue.

**Comment by lamafab** [comment]
@FlorianFranzen will review network messages.

**Comment by lamafab** [comment]
@FlorianFranzen is almost done with this. Will complete this soon.

**Comment by FlorianFranzen** [comment]
Outstanding network encoding issues can be found in soramitsu/kagome#773 and soramitsu/kagome#774.
