### ISSUE TITLE
Investigate epoch descriptor

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#173]
Investigate the role of the epoch descriptor defined here:

https://github.com/paritytech/substrate/blob/master/client/consensus/epochs/src/lib.rs#L212

And spec if it is necessary for the spec to contains it.

**Comment by FlorianFranzen** [comment]
According to the current host spec and the BABE research write up, the slot number is supposed to be reset at the beginning of each epoch.

Substrate does not do this, so it needs epoch descriptors to tracks the slot number at the beginning (and end) of each epoch. Therefore there is no need to add them to the spec at the moment.

**Comment by drskalman** [comment]
the original description for the developer is:
"A new post-digest type NextConfigDescriptor is added. This descriptor can only be used at epoch transition, on the same block as NextEpochDescriptor. NextConfigDescriptor is optional, and modifies the config value of c and allowed_slots of the next upcoming epoch (same as the block NextEpochDescriptor points to)." in Issue #46

**Comment by FlorianFranzen** [comment]
Indeed I think we closed this too soon. While we might not have to spec the `ViableEpochDescriptor`, we should take another look at the [`NextEpochDescriptor`](https://github.com/paritytech/substrate/blob/master/primitives/consensus/babe/src/digests.rs#L122).

**Comment by FlorianFranzen** [comment]
This is included in #168 now.
