### ISSUE TITLE
Make removing seal digest more explicit

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#178]
Make a note in general but also in execute block that seal should remove before it is submitted to runtime in any occasion. There was a discussion about this in the channel:

 "can we please specify how import should be done? Now it is implemented mostly based on discussions in chat. And we have issues with that. So I want to make sure we did everything correctly
 For example now I am not sure if spec covers that we should remove last digest containing seal before invoking Core_execute_block. Probably there are some other things that we should be aware of"
￼
"It is in Algorithm 6.5 Verify-Authorship-right
but maybe we should mention it also in execute block [as well]"

**Comment by lamafab** [comment]
Fixed with PR #175.

**Comment by drskalman** [comment]
to be reviewed by @drskalman
