### ISSUE TITLE
Start a XCMP chapter in the runtime spec

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#187]
The chapter should be similar to the AnV chapter (availability_and_valaidity chapter in ./runtime-spec/),  have a section for each step of the XCMP protocol and a plantuml flow chart for describing the process.

   using the XCMP write up from here:

   https://w3f-research.readthedocs.io/en/latest/polkadot/XCMP.html

   and put the initial skeleton and place holders in place.

**Comment by drskalman** [comment]
@LeonGB is updating it on the research side so we should keep in contact.

**Comment by drskalman** [comment]
We have a meeting with @LeonGB and we start the structure after.

**Comment by drskalman** [comment]
** TODO add a test for trie root with keys that are longer than 32 bits :w3f:pdre:
   :PROPERTIES:
   :GH_URL:   https://github.com/w3f/polkadot-spec/issues/176
   :GH_OWNER: w3f
   :GH_REPO:  polkadot-spec
   :GH_ISSUE_NO: 176
   :END:
   Kogame implementation had a bug related to this and so it is helpful to check if an implementation is doing fine with longer keys

**Comment by drskalman** [comment]
- @FlorianFranzen starts next week.

**Comment by drskalman** [comment]
- Florian had a call with Leon.
- Florian is reading up on CST (channel state table). is going to add it the flow chart and will be ready for review.
- Next meeting on Friday.

**Comment by drskalman** [comment]
@FlorianFranzen had a meeting on Monday. Has rough draft.

**Comment by drskalman** [comment]
@FlorianFranzen will share the draft with @LeonGB and maybe link it to this issue.

**Comment by drskalman** [comment]
@FlorianFranzen will merge the current write up and put the issues on hold till open/close channel is designed.

**Comment by drskalman** [comment]
XCMP and AnV are going to be part of Parachain Validation spec.

**Comment by drskalman** [comment]
@FlorianFranzen will update this by the end of the week.

**Comment by FlorianFranzen** [comment]
HRMP is currently prioritized over XCMP, so this has all come to a hold for now.
However I will collect Fabio's and my work so far into an initial draft for a parachain spec as part of our effort to establish a regular release cycle.

**Comment by lamafab** [comment]
@FlorianFranzen Merge this together with the rest in #287.

**Comment by FlorianFranzen** [comment]
Most of the information has either become outdated or is already included in Fabio's updated graph. The few remaining things were merge with #287.
