### ISSUE TITLE
Verify Grandpa Voting message definition and clarify Voter Set Id

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#195]
The relevant questions from the implementor is ", it looks like some brackets are missing from the equation, could you clarify what is in the signature part of the message? why is stage included twice? also, could you clarify what V_id is: Vid: incremental change tracker counter"

**Comment by drskalman** [comment]
- [ ] Add primary propose message to the grandpa spec
   - [ ] We always precommit to the ghost, if no ghost then to the base.
   - [ ] Replace the definition of prevoted block with prevote GHOST.
   - [ ] Fix Best-PreVote-Candidate.

**Comment by drskalman** [comment]
- [X] Add primary propose message to the grandpa spec
   - [X] We always precommit to the ghost, if no ghost then to the base. SHouldn't ghost >= base be true.
   - [X] Replace the definition of prevoted block with prevote GHOST.
   - [X] Fix Best-PreVote-Candidate.

**Comment by drskalman** [comment]
^ 7f46b4c - Best-Prevote-candidate is the GHOST - Example of non-finalized final candidate added.

**Comment by drskalman** [comment]
Could @lamafab kindly takes care of Issue #130 now that he is at it?

**Comment by lamafab** [comment]
Issues fixed in #202

**Comment by drskalman** [comment]
f0a0b3fead92204fa830213e0b6c90d9e8188a4c :
 - Delay voting period in Grandpa statistically specified.
 - Honest scenario for best candidate not finalized added to grandpa example.
