### ISSUE TITLE
Use the design document from the implementers to update AnV Spec

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#197]
We should use this implementators guide 
https://github.com/paritytech/polkadot/blob/master/roadmap/implementors-guide/guide.md

to update mising Definitions and TBS algorithms in the AnV documents and probably adding and specing more algorithms which can be found in the document and is not in the Spec.

**Comment by drskalman** [comment]
New location of the document  is: https://github.com/paritytech/polkadot/blob/master/roadmap/implementors-guide/guide.md

**Comment by lamafab** [comment]
The guide transitioned to [mdBook](https://github.com/paritytech/polkadot/tree/master/roadmap/implementors-guide).

**Comment by drskalman** [comment]
@lamafab will focus more on filling up the TBS as the implementor's guide doesn't help much with those.

**Comment by drskalman** [comment]
On hold and we visit this after the guide gets updated.

**Comment by lamafab** [comment]
Largely done. Closing on behalf of #468
