### ISSUE TITLE
Draw the main flow charts for the XCMP protocol

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#201]
Similar to the [AnV flow chart](https://github.com/w3f/polkadot-spec/pull/199) we need one or three for the XCMP protocol. We are planning to make  3 charts for the following proces
  - [ ] Send.
  - [ ] receieve.
  - [ ] verify receive.

**Comment by drskalman** [comment]
The flow charts are included in the draft related to issue #187

**Comment by lamafab** [comment]
Part of #287 

(work-in-progress)
![image](https://user-images.githubusercontent.com/42901763/96427122-75c2d400-11fe-11eb-9986-e61dbc05b5ec.png)
