### ISSUE TITLE
Spec failure mode of ext_crypto_*_generate

### ISSUE THREAD

**Issue by FlorianFranzen** [w3f/polkadot-spec#208]
Based on a question from Soramitsu: Specification says, that it should return simple i32 pointer to generated data, but what if it has to return error? e.g. key type id or the seed parameter can be invalid. What should it return in this case?

**Comment by FlorianFranzen** [comment]
Substrate currently [panics on error](https://github.com/paritytech/substrate/blob/d65e6443c8281ff65fa5d39cbd454afa2624390e/primitives/io/src/lib.rs#L389).

**Comment by lamafab** [comment]
Included in #239.
