### ISSUE TITLE
Spec offchain api

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#21]
Offchain api consists of new set of functions in Runtime Environment API which
and need to be specced. Only Submit_transaction has been specced.
https://github.com/paritytech/substrate/blob/master/core/executor/src/wasm_executor.rs#L930
https://github.com/paritytech/substrate/blob/master/core/executor/src/wasm_executor.rs#L930

**Comment by drskalman** [comment]
I merged most changes and added some explanations: https://github.com/w3f/polkadot-spec/commit/b47293bfbbdd2323076b5bc8984addcc548589ac

- Could you check the accuracy of what I wrote?
- There are some new todos.
- The "when you are allowed to call append header" is still there which I think is related to @tomaka 's comment as well.
- I made independent issue #60 .
- I changed your labels (added defn) to follow the other labeling in the doc.

**Comment by lamafab** [comment]
Thanks Syed, I'll work on that!

**Comment by lamafab** [comment]
Multiple PRs were done for this: #48, #64, #66
