### ISSUE TITLE
Spec should mention the Seal log item addition/removal

### ISSUE THREAD

**Issue by tomaka** [w3f/polkadot-spec#216]
In Substrate's code, when we import a block, we first pass it to Aura or Babe.
Aura/Babe look in the block's header for a `Seal` log item, and if one is found they remove it before calling `Core_execute_block`. Then it has to be put back before inserting the block in the database.

Similarly, when producing a block, the runtime does not generate a `Seal` log item. Aura/Babe should do a post-generation-pass to add their seal.

cc @andresilva

**Comment by FlorianFranzen** [comment]
This is mentioned in section 3.3.1.1 ...
![Section 3.3.1.1](https://user-images.githubusercontent.com/781077/105208040-8b6ecf00-5b48-11eb-8423-5b15aa21528f.png)

... and section G.2.2. 
![Section  G.2.2](https://user-images.githubusercontent.com/781077/105208042-8c076580-5b48-11eb-9534-a9e82a2bc2b3.png)

@lamafab Will add additional details details to Algorithm 6.7.
