### ISSUE TITLE
Some mistakes or outdated information in the specs

### ISSUE THREAD

**Issue by tomaka** [w3f/polkadot-spec#217]
Here is a list of mistakes or outdated information I've found in the specs:

- [x] Section G.2.2. mentions that `Core_execute_block` returns a boolean. It actually returns nothing. The runtime indicates a failure by trapping rather than returning `false`.

- [x] Section E.6.2 mentions that "The keys are little-endian, fixed-size integers". The keys are actually the SCALE-compact encoding of the index in the list. (https://github.com/paritytech/substrate/blob/b3e0cb68129eef29fd4521b23c39d1c8dd2e28cf/primitives/trie/src/lib.rs#L75) For example the key of the first element in the list is a SCALE-compact-encoded `0`.

- [x] The `ext_storage_append_version_1` function is missing from the specs. It expects as parameter a key and value (similar to `ext_storage_set`). It consists of three steps: load the storage item with the given key, assume that the existing storage item is a SCALE-encoded `Vec` and that the given value is a SCALE-encoded item of that vec, and add the given value to the end of that `Vec`. If the existing value is missing or is not actually an encoded `Vec`, store a one-length `Vec` with the given value.

- [x] This one might require messaging some people because I didn't manage to figure this out myself. The specs mentions that the `ext_storage_root_version_1` function returns the SCALE-encoded hash (so, one byte of length and 32 bytes with the hash itself). However, in practice, the runtime seems to expect the hash to be directly returned (32 bytes, without any length prefix). The weird thing is that it seems that Substrate's source code agrees with the hash being SCALE-encoded. I haven't tried the `ext_storage_changes_root_version_1` function, but it might be the same.

- [x] The `ext_crypto_start_batch_verify_version_1`, `ext_crypto_sr25519_verify_version_2` and `ext_crypto_start_batch_verify_version_1` functions are missing from the specs. Many other functions are missing, but these three are used basically all the time by the runtime.

- [x] Definition 2.11 mentions `scale_encode(storedvalue(kn))`. Definition 2.1 mentions that `storedvalue` is empty if the node doesn't have any storage value. This has lead me to believe that `scale_encode(storedvalue(kn))`, when `kn` has no storage value, should be one byte of value `0`. In reality it should be nothing.

- [x] Definition 2.11 defines `svn` as bytes. In my opinion it should clearly mention that `childrenbitmap` should be the little-endian encoding of the value defined in definition 2.10. In other words, the first byte of `svn` should be `b7...b0` and the second byte of `svn` should be `b15...b8`.

- [x] Section G.2.1. is missing the `transaction_version: u32` field that was recently added: https://github.com/paritytech/substrate/blob/dbf2163250833e6ac898e7f6c3c8f89f08a7c19d/primitives/version/src/lib.rs#L107

- [x] Section G.2.1. mentions `ApisVec`, but this isn't defined anywhere (it's a `Vec<([u8; 8], u32)>`).

- [x] Section E.1.3. says that `offset` is a `i32`. It is in fact a `u32`. Negative offsets don't really make sense anyway.

**Comment by drskalman** [comment]
@lamafab will implement tests for the missing Host API functions.

**Comment by lamafab** [comment]
> Section E.1.3. says that offset is a i32. It is in fact a u32. Negative offsets don't really make sense anyway.

Wasm doesn't differentiate between i32/u32. Everything else in the Host API is documented as signed integers, so I'll just leave it as it is.

**Comment by tomaka** [comment]
> Wasm doesn't differentiate between i32/u32. Everything else in the Host API is documented as signed integers, so I'll just leave it as it is.

Wasm doesn't differentiate between i32 and u32 because it treats them as opaque 32-bits-long bits. Whether these 32 bits represent an unsigned or signed value depends on the upper layer and isn't important for the Wasm VM, but we're specifying the upper layers here, and so it's important to differentiate between i32 and u32.

**Comment by lamafab** [comment]
@tomaka Alright, I adjusted those two functions:
- ext_storage_read
- ext_storage_child_read

**Comment by bkchr** [comment]
>     * This one might require messaging some people because I didn't manage to figure this out myself. The specs mentions that the `ext_storage_root_version_1` function returns the SCALE-encoded hash (so, one byte of length and 32 bytes with the hash itself). However, in practice, the runtime seems to expect the hash to be directly returned (32 bytes, without any length prefix). The weird thing is that it seems that Substrate's source code agrees with the hash being SCALE-encoded. I haven't tried the `ext_storage_changes_root_version_1` function, but it might be the same.

As Substrate is generic, the hash could be anything and as the host interface can not be generic, we need to return a `Vec<u8>` that is the result of `hash.encode()`. When it comes to fixed length arrays like the hash type, we don't prefix it with the length, because they are fixed length.

The spec probably needs to say that the function returns a `Vec<u8>` using the default host interface encoding for such a type and this `Vec<u8>` holds the encoded hash value.

**Comment by bkchr** [comment]
https://github.com/paritytech/substrate/pull/6626 I hope this makes the docs more clear.

**Comment by lamafab** [comment]
Fixed in #239.

**Comment by drskalman** [comment]
@drskalman will review it.

**Comment by drskalman** [comment]
- spec needs to mentoin that runtime panic on executing bad block.

**Comment by lamafab** [comment]
>     * spec needs to mentoin that runtime panic on executing bad block.

Updated.

**Comment by drskalman** [comment]
@lamafab is going to merge it to master and produce the PDF.
