### ISSUE TITLE
Spec should mention the `__heap_base` symbol

### ISSUE THREAD

**Issue by tomaka** [w3f/polkadot-spec#218]
The `__heap_base` symbol is exported by the runtime and should be used as the base point for the external memory allocator.

It seems to me that the Wasm code is free to overwrite any memory below `__heap_base`, and it would thus be dangerous for the external memory allocator to not use this value.

https://github.com/paritytech/substrate/blob/0227ff513a045305efee0d8c2cb6025bcefb69ff/client/executor/common/src/error.rs#L69-L71

**Comment by FlorianFranzen** [comment]
We probably also want to mention that newer versions of the runtime are build `--import-memory` link-arg which is used when building newer runtimes.

Edit: Did some digging and opened a separate issue for this (#224).

**Comment by FlorianFranzen** [comment]
Fixed in #402.
