### ISSUE TITLE
Review GRANDPA Catch-up implementation in Gossamer

### ISSUE THREAD

**Issue by lamafab** [w3f/polkadot-spec#228]

**Comment by lamafab** [comment]
The full review of the Gossamer GRANDPA implementation is on [hackmd](https://hackmd.io/JPtCvFtQSOmNysqzfGPHow?view).

**Summary**
- [x] - Usage of ed25519 key pairs
- [x] - Call into Runtime `grandpa_authorities`
- [ ] - Track and increment Authority Set ID
	- **NOT COMPLIANT**
	- Chainsafe: getting fixed!
- [x] - Determine highest voted block
- [x] - Issue pre-vote
- [x] - Issue pre-commit
- [ ] - Issue catch-up messages
	- **NOT IMPLEMENTED**
	- Not high prio for now
- [ ] - GRANDPA Vote/Gossip
	- **NOT COMPLIANT**
	- Chainsafe: getting fixed!
- [ ] - Authority Set changes
	- **NOT COMPLIANT**
	- Chainsafe: getting fixed!
- [x] - Detect and report equivocation

**Comment by drskalman** [comment]
Waiting for repsonoses from Gossamer team.

**Comment by lamafab** [comment]
Updated:

- [x] - Usage of ed25519 key pairs
- [x] - Call into Runtime `grandpa_authorities`
- [x] - Track and increment Authority Set ID
	- Fixed!
- [x] - Determine highest voted block
- [x] - Issue pre-vote
- [x] - Issue pre-commit
- [ ] - Issue catch-up messages
	- **NOT IMPLEMENTED**
	- Not high prio for now
- [x] - GRANDPA Vote/Gossip
	- Fixed!
- [x] - Authority Set changes
	- Fixed!
- [x] - Detect and report equivocation

**Comment by lamafab** [comment]
Catch-up message are planned for the next grant. Closing this for now.
