### ISSUE TITLE
Spec the general internal structure of Polkadot transactions

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#229]
The polkadot host mentions that the host is agnostic about the internal structure of the transactions submitted to the Runtime beside expecting them to be SCALE encoded blob. Nonetheless several implementors asked for the internal of transaction partly because they need to submit transactions to their nodes to test it. Therefore it seems to be a good to have the general structure of typical polkadot transaction being specced in the runtime spec (what is common between most transaction and perhaps not each individual type) so we can refer the implementors to it.

**Comment by lamafab** [comment]
See PR #250
