### ISSUE TITLE
Spec justification format and update its validation

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#23]

**Comment by drskalman** [comment]
For all that matters this seems to be defined in definition 6.37: https://github.com/w3f/polkadot-spec/blob/skalman-issue-22-reverse-branch-value-order/host-spec/c06-consensus.tm#L1252. I'll double chcek these two:

 - [ ] This definition is referred to in the chapter 6 when block import is described.
 - [ ] Look into full client code to see if it matches with what the client expect when it import the block from corresponding network message.

**Comment by lamafab** [comment]
@drskalman will submit this to @lamafab for review.

**Comment by drskalman** [comment]
The pull request requires some verification by @lamafab

**Comment by FlorianFranzen** [comment]
PR #334 was reviewed and merged.
