### ISSUE TITLE
AnV and XCMP needs to moved out of runtime spec

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#230]
They are not implemented as part of runtime wasm and therefore needed to be implemented by other implementers as well. As so they needs to be moved to host-spec folder. Perhaps a subfolder as "validator/validation spec". Assigned to @FlorianFranzen because he deals with the CI which might be affected by this.

**Comment by FlorianFranzen** [comment]
Implemented as part of #287.
