### ISSUE TITLE
Clarify blocking calls storage_root in Kagome implementation

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#231]
Host doesn't seem to be able to block calls to API. Investigate why they have blocked it. Either update spec or/and ask them to change implementation.

**Comment by drskalman** [comment]
There was an extensive discussion about this in spec channel. The most relevant ones are:

"pierre-tomaka
I don't really understand the point of specifying that storage_root commits the changes. If a node commits the changes at every single storage write, it works as well.
If you specify that the database should be written when storage_root is called, you're essentially saying "well, the node will be in a bad state if the runtime traps afterwards"

"Émeric (cheme)
I have a bit of a hard time following the conversation here, but if I had to spec ext_storage_root, I would just say that it return the root with the current pending change.
The fact that we internally store the trie update (cache) and push them with the block change set if cache was not invalidated (eg when call in finalize) is implementation strategy to avoid calculating the trie change twice.
"

@FlorianFranzen could you update it based on above and then check with @lamafab if he agrees with the updated verision. Plus could you follow up with Kagome to fix their implementation? maybe you can make a gitlab issue for them.

**Comment by drskalman** [comment]
@FlorianFranzen says not only the function is blocked to call but it even when it gets called it returns zero.

**Comment by drskalman** [comment]
So for now we know Kagome wasn't implemented correctly now we should investigate if it is corrected after updating the spec.

**Comment by FlorianFranzen** [comment]
Fabio update the spec accordingly in 3c63b6e and Soramitsu seems to have fixed the issue a few weeks ago in Kagome.
