### ISSUE TITLE
Specify Babe's secondary slots

### ISSUE THREAD

**Issue by FlorianFranzen** [w3f/polkadot-spec#233]
There are currently [two secondary slot modes](https://github.com/paritytech/substrate/blob/18334ee173f0ec4b62d2ca05c5b0c1f0b05b1b17/primitives/consensus/babe/src/lib.rs#L218-L227) in substrate and both are in use (plain in Kusama, VRF in Polkadot).

**Comment by FlorianFranzen** [comment]
I updated the spec in #168 to at least correct the encoding of the secondary slot in the genesis configuration and for configuration update digests. 

Current status is that the secondary slot will not be specified for now, as there will be no secondary slot in _Sassafras_, which should replace _Babe_ in the long run.

**Comment by FlorianFranzen** [comment]
Given the delay with __Sassafras__, we should add these details to the spec.

**Comment by lamafab** [comment]
Fixed in #491
