### ISSUE TITLE
Review AnV algorithms

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#235]
Review and Polish the AnV algorthms including the level detail specified.

**Comment by FlorianFranzen** [comment]
Fabio takes this over after reviewing Network and Grandpa/Beefy.

**Comment by drskalman** [comment]
@lamafab is comparing with Comulus and Polkadot Primitive codes and update the spec accordingly.

**Comment by drskalman** [comment]
@lamafab will decide if the charts in pull request #449 are useful.

**Comment by drskalman** [comment]
@lamafab restructured the section parachain block prodoction (creating candidate etc). basically done. 
added runtime api section. currently writing candidate backing.

**Comment by lamafab** [comment]
Closing in favor of #468
