### ISSUE TITLE
Inculde all Specification from PoV presentation into AnV spec

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#238]
This includes all data types and function parameters specified in the Presentation which can be found here:
   https://drive.google.com/file/d/1p9FxhulFTlo43fE-DEN_nJv6B7Fbq6OT/view?usp=sharing

**Comment by drskalman** [comment]
what left is validate_candidate and related functions to be specced.

**Comment by lamafab** [comment]
Closing on behalf of #468
