### ISSUE TITLE
Review the VRF implementation of gossamer

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#243]
Review and compare the VRF implementation of the BABE VRF in gossamer vs Schnorrkel.

**Comment by FlorianFranzen** [comment]
While Kagome uses [sr25519-crust](https://github.com/Warchant/sr25519-crust) which just wraps Schnorrkel, Gossamer actually uses a Go bases Schnorrkel clone [go-schnorrkel](https://github.com/ChainSafe/go-schnorrkel), that probably will need a proper audit at some point.

**Comment by Noc2** [comment]
Done
