### ISSUE TITLE
Core_execute_block should return useful error code in case of failure

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#246]
It is OK for core_execute_block to panic facing a non-recoverable error, but whenever it is possible, it is always better for the runtime to return a useful information about the error to the host instead of simply paniccing.

**Comment by lamafab** [comment]
Opened https://github.com/paritytech/substrate/issues/6716

**Comment by lamafab** [comment]
Closing. See https://github.com/paritytech/substrate/issues/6716#issuecomment-673530177
