### ISSUE TITLE
Specify Upward/Downward Message Passing protocol

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#260]
the reference for it can be found here: 
   https://github.com/paritytech/polkadot/pull/1503

   as described in the implementer's guide.

**Comment by drskalman** [comment]
The protocol when used for inter parachain comms is called HRMP.

**Comment by lamafab** [comment]
Current work is on the `hrmp-xcmp-spree-spec` branch. 

https://github.com/w3f/polkadot-spec/blob/hrmp-xcmp-spree-spec/host-spec/parachains/messaging-spec.md

The basics of UMP/DMP are defined, but this is an ongoing process where additional changes are still to come:
- https://github.com/paritytech/polkadot/issues/1642
- https://github.com/paritytech/polkadot/issues/1663

Closing this ticket for now and will open new ones.
