### ISSUE TITLE
Prepare a HackMD document for libp2p interoperability problem

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#261]
The document should describe the problem, demonstrate discrepancy between implementation, steps we took to involve the upstream, and our plan of action due to lack of interest from them.

**Comment by drskalman** [comment]
@Noc2 could you simply start the hackmd, leave the link here and then re-assign the issue to @FlorianFranzen to start the text.

**Comment by drskalman** [comment]
I forgot I promised to make the hackmd myslef :-P

**Comment by drskalman** [comment]
Here is the hackmd.  https://hackmd.io/L0TfbtPoQ-yrc0xSRHNazA?both

**Comment by lamafab** [comment]
@FlorianFranzen will talk with Soramitsu, @infinity0 and ChainSafe to figure out the interoperability problems and write the required spec in order to fix those.

**Comment by lamafab** [comment]
@lamafab @FlorianFranzen  organize a meeting with @infinity0 and discuss this.
