### ISSUE TITLE
Rename Runtime env to host in the over view paper

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#265]
The [overview paper](https://github.com/w3f/research/tree/master/docs/polkadot/Polkadot-OverviewPaper) still refers to Polkdot host as Polkadot Runtime enviornment and this need to be fixed.

**Comment by FlorianFranzen** [comment]
I think I already fixed the overview paper earlier with [PR #93](https://github.com/w3f/research/pull/93), but I guess that did not update the version published online.

**Comment by FlorianFranzen** [comment]
I updated the PDF version in the research repo in w3f/research#96, updating the version on arxiv.org is left to do by research at their own convenience.
