### ISSUE TITLE
Correct the problem with calling mistakenly transaction, extrinsic in the extrinsics section

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#27]
When the Extrinsics section is written with the confusion that the inhernts can be gossiped on the 
network this is not true however, So in many places "Extrinsic" can be replaced by "Transaction".

**Comment by drskalman** [comment]
It is needed for answering chainSafe question #73

**Comment by FlorianFranzen** [comment]
Seems #73 is done. Any update on this?

**Comment by lamafab** [comment]
@drskalman will check this out next week (after the BABE review).

**Comment by lamafab** [comment]
@drskalman will continue on this after his environment is setup.
