### ISSUE TITLE
List all progress of Spec group for the month of August

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#271]
This should happen monthly but till we have a processes I'll make an issue for the month of August, till we have a process for it:
https://docs.google.com/document/d/1crc5h6tbmn04ywNBAPIzVfwXx7jMkbw0xMsFt-Bx5sQ/edit?ts=5f45b359#heading=h.k4phwljfr676

**Comment by FlorianFranzen** [comment]
I wrote a little overview earlier. 

@drskalman and @lamafab, do you have any to add?

**Comment by drskalman** [comment]
Done tasks:
 - Host spec was updated to specifies motivation and example for child storage.
 - Blocking calls to storage_root in Kagome was investigated, implementator was asked to update behavoir and  specification regarding storage updates was clarified to avoid future confusions.
 - Consensus chapter of Host Spec was updated to the latest changes in Babe specification.
 - Several corrections and updates was submitted to the Spec group which has been unearthed during re-implementation of Polkadot in Rust. All has been investigated corrected and Host Spec was updated accordingly.
 - Specification of 'configuration' Runtime entry was updated to the lastest changes
 - General internal structure of Polkadot transactions has been specification as requested by several implementers.
 - Force and Epoch Changes in Authority set was more clearly specified.
 - kagome-adapter: Implement host-api fixture testsuite
 - kagome-adapters: Use wasm-adapter testsuite
 - Comperhensive discussion was conducted among the spec team and implementors for "Core_execute_block" runtime entry to  return more useful error code in case of failure but was not deemed necessary.
 - Failure mode of "ext_crypto_*_generate" Runtime entry was specified.
 - Handling of forks by Kagome storage was reviewed.
 - storage root test was extended to check initial root and storage content.
 - false positives from HostAPI fixtures testsuite was removed.

Unfinished Progresses:
 - Spec team started specifying the XCMP protocol but put on pause as HRMP was deemed to be higher priority.
 - Updating K Spceification Balance Palett to latest version.
 - Documenting libp2p interoperability problems.
 - Specifying BABE Temporary Clock Adjustment specification
 - Automating the release process of Host Specification.
 - Re-organizing of the Specifications of AnV and XCMP protocols.
 - Reviewing and verifying the milestone of Runtime verification grant.
 - Benchmark the time footprint of calling host api functions in wasm blobs
 - Reviewing of implementors agreements
 - clarifying network messages specification
 - Specifying Upward/Downward Message Passing protocol specification
 - specifying the transaction weight system and the rational behind it.
 - Specifying changes trie.

**Comment by drskalman** [comment]
@FlorianFranzen could you please review it, fix it, add anything that I overlooked and move it the tech upadte google doc?

**Comment by FlorianFranzen** [comment]
Done for August (see link to document in description)
