### ISSUE TITLE
Message Passing: spec XCMP and SPREE.

### ISSUE THREAD

**Issue by lamafab** [w3f/polkadot-spec#282]
Spec functionality of XCMP and SPREE in the runtime spec.

**Comment by drskalman** [comment]
@drskalman is going to gather all the notes on the SPREE, verify it with @AlistairStewart and follow up with the devs.

**Comment by drskalman** [comment]
The current write up is in the host-spec pull request of @FlorianFranzen .

**Comment by lamafab** [comment]
Current progress in #287. I will open new issues when changes are added.
