### ISSUE TITLE
Gossiping and queuing transactions: How much spec should mandate

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#284]
How much should be mandated by the spec, 
    - should it be just as much as it make it to a block producer or everybody should just gossip it as far as possible?
      One should be able to submit the transaction to one producer node and that should be enough and nobody needs to gossip further.
      Gossip should be extension.
      How to Gossip: should be specified in an implementer guide.

    - is transaction Queuing strategy is part of Spec.

**Comment by drskalman** [comment]
- [x] At least mention having two sets of submitted and validated and ready to apply transaction (meaning all required tags are provided) and apply only from the second set based on tag and prioritization.
- [x] update the return value from validate_transaction (including logivity).

**Comment by FlorianFranzen** [comment]
@lamafab will spec the missing `Maintain-Transaction-Pool` algorithm (Algorithm 3.3. in host-spec) including checking _Longevity_.

**Comment by burdges** [comment]
We'll want to change or kill the memepools post sassafras btw

**Comment by lamafab** [comment]
This is implementation specific and outside the scope of the spec.
