### ISSUE TITLE
Specify the parameters and return values for all Runtime entries in Polkadot wasm

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#30]
Currently only Core_execute_block and validate_transaction has been specified.

**Comment by FlorianFranzen** [comment]
There has been a lot of work on the PDRE/PDH. Is this till relevant?

**Comment by drskalman** [comment]
I don't think so. I think we decided to spec param and return values of FRAME functions we need to call while specifying spec. I believe all of them (which are referred to by algorithms) and there and their param and return values are specified according to current runtime implementation. @lamafab could you double check if enteries specified in Appendix G, indeed are in sync with the current runtime implementation and close this issue after? thanks  a lot.

**Comment by drskalman** [comment]
This is covered by #328. @lamafab will close it when is done with #328

**Comment by lamafab** [comment]
Closing in favor of #328.
