### ISSUE TITLE
Update W3F Tech Updates and Strategies for Spec team

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#305]
- [x] Tech Update: https://docs.google.com/document/d/1crc5h6tbmn04ywNBAPIzVfwXx7jMkbw0xMsFt-Bx5sQ/edit#
 - [x] Prepare slide for Counsel Meeting: https://docs.google.com/presentation/d/183B7xkLOkF7TrgrkasNgZkJEGXpMCHqu0g5HUc7FeLU/edit#slide=id.g7297805f94_0_77
 - [x] Strategies: https://docs.google.com/document/d/1pRR6TItMebRpBwv1wmBLR4qVaDG52s1QBFxf0TBf8P0/edit#heading=h.4qibwv9t9e8z
See notes from strategy meeting: https://gitlab.w3f.tech/spec/polkadot-spec-internal/-/issues/1#note_1420

**Comment by lamafab** [comment]
@FlorianFranzen will continue on this asap.
