### ISSUE TITLE
Update RPC methods

### ISSUE THREAD

**Issue by lamafab** [w3f/polkadot-spec#306]
Update the latest PRC methods and adjustments: https://github.com/w3f/PSPs/pull/6

**Comment by FlorianFranzen** [comment]
You might also want to add the fact that on subscription the current state is sent once, so a subscriber newer has to query the current state.

**Comment by lamafab** [comment]
@lamafab will continue on this asap.

**Comment by lamafab** [comment]
@FlorianFranzen will review this.
