### ISSUE TITLE
Host-Spec: Fix SVG conversion

### ISSUE THREAD

**Issue by FlorianFranzen** [w3f/polkadot-spec#309]
Currently TeXmacs uses tex to convert the svg graphs to eps before building the host spec pdfs. However this process leaves artifacts on the resulting eps file ("viewed does not support SVG 1.1") and even fails on CI. This needs to be fixed.

**Comment by drskalman** [comment]
Maybe we store them in EPS format to begin with. We ask @lamafab if he can do that. Otherwise, the make file can check if inkscape is there, then covert them otherwise uses commited EPS's.

**Comment by lamafab** [comment]
We will use PDFs. @FlorianFranzen will continue on this. @lamafab will test it once done.
