### ISSUE TITLE
Update grandpa joining algorithm

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#31]
to comply with what actually is implemented

**Comment by drskalman** [comment]
it is Section 6.3.3 though the text can use some edits. I'll fix that and close this issue.

**Comment by lamafab** [comment]
@lamafab Check the substrate codebase for this https://github.com/paritytech/substrate/blob/master/client/finality-grandpa/src/lib.rs#L864

Regarding spec: how does a voter that just joined know about past votes?
