### ISSUE TITLE
problems with the Code Executor section 

### ISSUE THREAD

**Issue by pepyakin** [w3f/polkadot-spec#312]
There are some problems with it.

> Afterwards, it needs to copy the byte array B value in the correct offset of the extended buffer.

What is the correct offset here? How one determines that? substrate-lite implementation went with implementation of copying the data right next `__heap_base` and it worked (at least to some degree). The big substrate involves the allocator to allocate the input data buffer (thus, finding the "correct offset").

Next, `__heap_base` nor the allocator are mentioned in the spec.

There are also some nits on the terminology: I think it would be better to rely on the definitions given by the [wasm spec](https://webassembly.github.io/spec/core/).

**Comment by FlorianFranzen** [comment]
Thank you for your feedback. Indeed the section could be improved.

> Next, `__heap_base` nor the allocator are mentioned in the spec.

This has also already been reported to us in #218.

**Comment by pepyakin** [comment]
> This has also already been reported to us in #218.

ah, great! although that's only `__heap_base` and I think the description of allocator (at least high-level) is very important.

**Comment by FlorianFranzen** [comment]
I will see that the section gets extended, including my recent experience with #351.

**Comment by FlorianFranzen** [comment]
Fixed in #402.
