### ISSUE TITLE
Specifies Algorithm 3.3 Maintain-Transaction-Pool

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#319]
The algorithm is scaning the pool for ready transactions and moving them to the TQ and dropping transactions which are not valid.

**Comment by lamafab** [comment]
@lamafab will work on this.

**Comment by FlorianFranzen** [comment]
@lamafab Please also update #29 when you are done with this.

**Comment by lamafab** [comment]
Maintaining the transaction pool is implementation specific and outside the scope of the spec.
