### ISSUE TITLE
Complete documentation of Host APIs

### ISSUE THREAD

**Issue by lamafab** [w3f/polkadot-spec#327]
Extend the spec with the latest Host API which are required to fully execute the Polkadot runtime.

**Comment by lamafab** [comment]
Fixed in #333.

**Comment by FlorianFranzen** [comment]
Does this also contain #307?

**Comment by lamafab** [comment]
> Fixed in #333.

To clarify, the Host APIs have already been covered, including the Offchain APIs. So #333 does not add any additional changes to that section. Issue #307 is fixed in #362.
