### ISSUE TITLE
Fix GRANDPA catchup and Initiating the GRANDPA State text

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#329]
Whenever a Polkadot node detects that it is lagging behind the ﬁnality procedure and therefore needs to
initiate a catch-up procedure. Neighbor packet network message (see Section D.1.7) the round number for the
last ﬁnalized GRANDPA round which the sending peer has observed.

Initiating the GRANDPA State
A validator needs to initiate its state and sync it with other validators, to be able to participate coherently in
the voting process. In particular, considering that voting is happening in diﬀerent rounds and each round of
voting is assigned a unique sequential round number r v , it needs to determine and set its round counter r in
accordance with the current voting round r n , which is currently undergoing in the network. Algorithm 6.8

**Comment by burdges** [comment]
Around catch up https://github.com/paritytech/substrate/issues/7398#issuecomment-728875053

**Comment by drskalman** [comment]
This is about the English quality of the text and should be fixed by 2028ca3.
