### ISSUE TITLE
Update the spec page on the research website

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#332]
# Spec related changes

 - [ ] General intro to Polkadot Spec: What is it all about.
 - [ ] General intro to Spec team and its work.
 - [ ] Intro into testing harness developed by the spec team.
 - [ ] An intro into host spec (publication on the page).
 - [ ] Put spec team members under publications in alphabetic order

# General changes

 - [ ] Remove redirect to empty overview page
 - [ ] Link to forum in menu and under publications
 - [ ] Remove or extend multisig page
 - [ ] Move all "todos" to issue tracker

**Comment by FlorianFranzen** [comment]
We should also add the spec team to the members page.

**Comment by FlorianFranzen** [comment]
The structure for this was added in w3f/research#114, I will add the content in the weeks to come.

**Comment by lamafab** [comment]
@FlorianFranzen is working on this with @jonasW3F -> fix broken links, improve CI, etc. @FlorianFranzen will prioritize the [overview paper](https://github.com/w3f/polkadot-spec/issues/405) first, though.

**Comment by Noc2** [comment]
I fixed the link today (on the new website).

**Comment by lamafab** [comment]
Only took 2.5 years, not bad.

**Comment by Noc2** [comment]
@0xCaso and I are currently updating the website: https://research.web3.foundation/
