### ISSUE TITLE
Clarify that difference between extrinsic validity and failure of its Runtime module call

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#337]
See relevant coversation regarding the confusion:

harrm
Hello. Could you please clarify, should the extrinsics for which apply_extrinsic returned DispatchError be included into the block? Because I ran into a weird behaviour where excluding them makes the extrinsic root differ from the one in the header after finalise_block.

Fabio
I'm not sure, actually. What was your experience?
￼
harrm
After applying an invalid extrinsic, for which apply_extrinsic returns DispatchError, I calculate the extrinsics root in the host code and compare it with the extrinsics root in the finalized header after finalize_block.  It doesn't match if the invalid extrinsic is not included in the block body, and does otherwise.

Fabio
Interestingly, DispatchOutcome is returned as Ok(...), while TransactionValidityError is returned as Err(...)
although, DispatchOutcome should be Ok(Ok(())) if everything is fine, while a dispatch error would be Ok(Err(...))

harrm
It breaks when I don't include the transaction with Ok(Fail) output from apply_extrinsic.

Fabio
ah, they even specify this in the docs:

/// This type specifies the outcome of dispatching a call to a module.
///
/// In case of failure an error specific to the module is returned.
///
/// Failure of the module call dispatching doesn't invalidate the extrinsic and it is still included
/// in the block, therefore all state changes performed by the dispatched call are still persisted.
///
/// For example, if the dispatching of an extrinsic involves inclusion fee payment then these
/// changes are going to be preserved even if the call dispatched failed.
pub type DispatchOutcome = Result<(), DispatchError>
/// Failure of the module call dispatching doesn't invalidate the extrinsic and it is still included
/// in the block, therefore all state changes performed by the dispatched call are still persisted.

we should adjust this in the spec

**Comment by drskalman** [comment]
This probably also involve describing the return value from `BlockBuilder_apply_extrinsic` in more detail.

**Comment by lamafab** [comment]
@drskalman It already is quite detailed:

![image](https://user-images.githubusercontent.com/42901763/103224400-eb969a80-4927-11eb-9683-76345a954e81.png)
![image](https://user-images.githubusercontent.com/42901763/103224456-fbae7a00-4927-11eb-8e71-9543b4425e5d.png)

**Comment by FlorianFranzen** [comment]
I think what is missing is what all of these failure cases mean concretely for the hosts, i.e. which extrinsics get included anyway, which ones get dropped and which ones are included in future blocks.

**Comment by lamafab** [comment]
Fixed in #363
