### ISSUE TITLE
Spec the SCALE of Error object

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#35]

**Comment by lamafab** [comment]
FYI: Multiple Error types in the Host APIs have been specced and are part of #119.

**Comment by FlorianFranzen** [comment]
@lamafab Are there any more error object we will need to cover?

**Comment by lamafab** [comment]
@FlorianFranzen No, API wise those are all. Also, this issue was about speccing the Rust type `Error` as SCALE, which is done.
