### ISSUE TITLE
The blobs in chain-candidates should be updated automatically

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#4]
The [Polkadot runtime](https://github.com/w3f/polkadot-re-tests/blob/master/polkadot-runtime/polkadot_runtime.compact.wasm) built by:

    $ git clone https://github.com/paritytech/polkadot.git
    $ cd polkadot
    $ git checkout v0.3
    $ git pull
    $ ./script/build.sh

Should be remade and pushed to the test repo everytime the runtime is get updated. 

Alternatively, it can be remade, when the test are made but it is rather costy and lengthy to do so everytime and the runtime doesn't get changed often.

We also keep a copy of the runtime in wat format. So it is necessary to regenerate the wat file everytime the runtime gets updated. This can be done using wasm2wat using wabt toolkit.

**Comment by drskalman** [comment]
The instruction for making [Polkadot runtime](https://github.com/w3f/polkadot-re-tests/blob/master/polkadot-runtime/polkadot_runtime.compact.wasm) is built by:

    $ git clone https://github.com/paritytech/polkadot.git
    $ cd polkadot
    $ git checkout v0.3
    $ git pull
    $ ./script/build.sh

Should be remade and pushed to the test repo everytime the runtime is get updated. 

Alternatively, it can be remade, when the test are made but it is rather costy and lengthy to do so everytime and the runtime doesn't get changed often.

**Comment by FlorianFranzen** [comment]
@drskalman: Is this still relevant?

**Comment by FlorianFranzen** [comment]
I just realized this is probably about the data we have in the `chain-candidates` directory, as the rest has already been automated.

**Comment by lamafab** [comment]
Not relevant for Milestone 3. @FlorianFranzen will work on this.

**Comment by FlorianFranzen** [comment]
Merged #340, which deletes chain candidates and redirects to upstream repo instead.
