### ISSUE TITLE
Pre-Publication Review of Host Spec

### ISSUE THREAD

**Issue by FlorianFranzen** [w3f/polkadot-spec#404]
# Skipped chapters:

- C07 AnV
- C08 Messaging

# Stage 1 - Spec Team

- [x] C01 Background @lamafab (#419)
- [x] C02 State @lamafab  (#419)
- [x] C03 Transition @FlorianFranzen (#439)
- [x] C04 Networking @drskalman (#435)
- [x] C05 Bootstrapping @FlorianFranzen
- [x] C06 Consensus  @drskalman  (#435)
- [x] A Cryptoalgorithms @drskalman (#446)
- [x] B Encodings @FlorianFranzen 
- [x] C Genesis @lamafab (#419)
- [x] D Hostapi @FlorianFranzen 
- [x] E Runtimeapi @drskalman (#446)

# Stage 2 - Research Team

- [x] C01 Background  @AlfonsoCev 
- [x] C02 State @AlfonsoCev 
- [ ] C03 Transition @AlfonsoCev 
- [x] C04 Networking @infinity0 -> #403
- [x] C06 Consensus @hndnklnc (through pdf/florian) @AlistairStewart (through Syed)

**Comment by drskalman** [comment]
- [ ] C04 network @skalman's review -> f3ee88da

**Comment by FlorianFranzen** [comment]
>     * [ ]  C04 network @Skalman's review -> [f3ee88d](https://github.com/w3f/polkadot-spec/commit/f3ee88da4868a9e3117f377adb409b02a8f31321)

This was included in #435. I updated the issue accordingly.

**Comment by drskalman** [comment]
Encoding is almost done. We might change the ordering based on @AlfonsoCev 's feedback.

**Comment by FlorianFranzen** [comment]
Apart from chapter 3, all chapters underwent some basic review.
