### ISSUE TITLE
Preliminary questions

### ISSUE THREAD

**Issue by bedeho** [w3f/polkadot-spec#42]
I have asked about the status of the spec in w3f/polkadot-re-spec#10, presuming its at a stage where asking concrete questions is meaningful, let me know if that's not the case.

# Questions

1. Algorithm 3 appears to be broken, 
   - `i` is never incremented?
   - `pk_{N}` should probably be in `pk_{N_i}`, otherwise the same partial key is added repeatedly?

2. `KeyEncode` and `StoredValue` show two conflicting presentations for showing the domain and range of a function, `StoredValue` is by far the most readable.

3. Def. 21 needs to be tightened up. `State Storage` is relied upon as a term, yet not formally defined (from what I see)

4. Def. 23 
   - uses an undefined single bar operator, is this meant to be array concatenation?
   - has an unnamed, unquantified variable `i`, not clear how to interpret this. Is this `i` related to the node traversal variable in Algorithm 3?
    - should `l_{pk_N}` is the length of the nibble array `pk_{N}`, so perhaps the naming `l_N`would be more succinct?

# Readability

For readability, I would suggest

- Always have backward-looking references for definitions, e.g. unlike Def. 25, this ensures that the conceptual apparatus is being built up in the natural reading direction. This is also the norm for most formal exposition, at least in my experience.

- Properly formalize what state storage is in some way. Have precise statements about what it means for things to be or not be in storage, along with keys, values, etc. Then define state tries and other apparatus as representing or corresponding to some state storage instance. This makes it possible to unambiguously talk about an isomorphism or content equivalence, as is attempted in Def. 21.  If not this, then at least something more robust then what is going on now. I now think I get what you are trying to do with this state storage concept, but it took too long to disambiguate.

**Comment by FlorianFranzen** [comment]
@bedeho Thank you for your questions. It seems all your questions were answered and I will close this issue for now. The spec underwent a lot of changes since you opened this issue, so please feel free to take another look and let us know if you have any other suggestions.
