### ISSUE TITLE
Spec Merkle Mountain Ranges

### ISSUE THREAD

**Issue by lamafab** [w3f/polkadot-spec#428]
Spec [Merkle Mountain Ranges](https://github.com/paritytech/grandpa-bridge-gadget/blob/master/docs/walkthrough.md#merkle-mountain-ranges), related to #331.

**Comment by lamafab** [comment]
Currently on hold. MMR/MMB will be specced later once the current implementation is more mature.

**Comment by heversonbr** [comment]
This is now fixed by [PR682](https://github.com/w3f/polkadot-spec/pull/682).
