### ISSUE TITLE
Remove appendix E

### ISSUE THREAD

**Issue by tomaka** [w3f/polkadot-spec#43]
It's always been intended that our networking protocol would change in the future. It shouldn't be specified yet.

**Comment by FlorianFranzen** [comment]
@tomaka In theory protocol labs should supply decent enough specifications, so that we could just refer to a list of modules and associated spec we expect each node to implement. It seems whoever we are not fully there yet.

**Comment by drskalman** [comment]
This is taken care of by #234 and we will close it when #234 get resolved.

**Comment by lamafab** [comment]
Closed in #333

**Comment by lamafab** [comment]
Closing, since this issue is outdated and the networking section is being overhauled.
