### ISSUE TITLE
Clarify how inherents are handled (incl. "inherent pools")

### ISSUE THREAD

**Issue by lamafab** [w3f/polkadot-spec#450]
Check substrate and maybe ask Parity. As discussed in the Strategy meeting.

**Comment by lamafab** [comment]
We already clarify in the [block production section](https://spec.polkadot.network/#sect-block-building) that how/which inherents are included, respectively `timstap0` and `uncles00`.

**Comment by bkchr** [comment]
> `uncles00`.

BTW, uncles inherent data isn't required.

**Comment by lamafab** [comment]
Yes, made that more explicit earlier today as part of #529
