### ISSUE TITLE
Spec VRF, transcripts, etc.

### ISSUE THREAD

**Issue by lamafab** [w3f/polkadot-spec#467]
Required for BABE and AnV (Approval Voting). Relevant links:

* https://docs.rs/merlin/3.0.0/merlin/index.html
* https://strobe.sourceforge.io/specs/

**Comment by drskalman** [comment]
current VRF changes are on the branch adjust-vrf

**Comment by drskalman** [comment]
turn make-bytes  into algorithm and spec internals of generate-challenge indepenedent of marlin and removing it: 04782be7

**Comment by lamafab** [comment]
Closed in #480
