### ISSUE TITLE
Spec Digest and Sealed and unsealed header

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#49]
Currently Digest is a vector of SCALEd byte arrays. We need to be more specific about DigestItem format. 
https://github.com/paritytech/substrate/blob/master/core/sr-primitives/src/generic/digest.rs#L77

At least we need to spec the seal and distingushed between sealed and unsealed header.

**Comment by FlorianFranzen** [comment]
The fact that the seal is not passed to the runtime in in the specification now and the details on digits item encoding was expanded.

I am still have to investigate how exactly _Consensus Messages_  in the digest are encoded. I will make the spec is clear on that.

Is there anything else that needs to be done for this?

**Comment by drskalman** [comment]
no further work than perhaps what @FlorianFranzen mentioned is required to close this. I'll assign it to @FlorianFranzen as such.

**Comment by burdges** [comment]
related https://github.com/paritytech/substrate/issues/7398

**Comment by lamafab** [comment]
@FlorianFranzen will review this.

**Comment by drskalman** [comment]
> I am still have to investigate how exactly Consensus Messages in the digest are encoded. I will make the spec is clear on that.

Definition 3.7 specifies digest items of varying data type. That is enough information about encoding of the Runtime to Consensus messages and I think we can close this issue.
