### ISSUE TITLE
Incoperate feedback from parity customer

### ISSUE THREAD

**Issue by FlorianFranzen** [w3f/polkadot-spec#492]
We received the following feedback on our spec through parity:

 - p.13 2nd paragraph "and is designed and be upgradable" - should be "and is designed to be upgradable"?

 - p.14 definition 1.6 the b's should have subscripted numbers, not exponentials? e.g. see 1.7

 - p. 17 2.1.2 4th paragraph "in a consistent with the Trie structure way"

 - p.25 3.1.2.4 2nd paragraph "any state changes resulting from Runtime enteries"

 - p.25 3.2.1 3rd paragraph "the internals of each intrinsics"

 - p.27 definition 3.6 "The header of block B, Head(B)" - there is already a definiton for "Head(B)" in definition 1.13 - this confused me.

 - p.29 alg 3.4 I believe "Set-Storage-State-At" is actually supposed to be "Set-State-At" ? For instance, see Definition 3.10 same page.

 - p.36 4th bullet "to perform information about blocks" - should be request, maybe?

 - p.48 def 6.11 confused me, "c ∈ (0,1)" - I did not grok that as the range of 0 to 1 but as the set of 0,1 "{0,1}?". This is probably a notational failure on my end but perhaps I'm not unique.

 - p.49 3rd paragraph from note 6.15 - "formal security analysis" is a pretty big claim, should back that up with a link to said analysis.

- p.64 7.2 Preliminaries - "The SCALE codec is defined in a separate document known as ``The Polkadot Host - Protocol Specification''. - Infact, that's the very document we're reading, should probably link to the appendix B.

Thank you, anonymous customer. We appreciate your time you spent providing us with this.

**Comment by lamafab** [comment]
This definition is kind of weird anyway, no (the bottom part)?

![image](https://user-images.githubusercontent.com/42901763/160384604-4c306c9a-c4f1-4bed-8a44-aa203dbf6a2f.png)

**Comment by FlorianFranzen** [comment]
> * p.27 definition 3.6 "The header of block B, Head(B)" - there is already a definiton for "Head(B)" in definition 1.13 - this confused me.

This is the last remaining point. Will be addressed in a separate PR. Everything else was fixed in #494.

**Comment by FlorianFranzen** [comment]
Remaining issues were fixed in #499.
