### ISSUE TITLE
Update BABE to the latest changes from pull 3611

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#50]
This include changes to the Weight definition, and the fact that babe uses ntp at intial lunch till gets enough blocks (that is 1200).
https://github.com/paritytech/substrate/pull/3611

**Comment by FlorianFranzen** [comment]
@drskalman It seems to me that all of this has been documented by now.

**Comment by FlorianFranzen** [comment]
Should be all included in #168.
