### ISSUE TITLE
`/ipfs/id/1.0.0` is not *really* a request-response protocol

### ISSUE THREAD

**Issue by tomaka** [w3f/polkadot-spec#527]
The spec mentions that in a request-response protocol, the initiator sends a single message containing the request and that this request is prefixed with its length.
This is indeed accurate, for all protocols except for `/ipfs/id/1.0.0` (because it was designed by Protocol Labs and not Parity).

For `/ipfs/id/1.0.0`, the initiator doesn't send any message at all, not even a `0`. The sending side of the initiator of the substream can be immediately closed.

**Comment by lamafab** [comment]
Fixed in #529
