### ISSUE TITLE
incorrect return value types of ext_storage_root in Host API

### ISSUE THREAD

**Issue by bhargavbh** [w3f/polkadot-spec#532]
It appears that the return type for both the versions of ext_storage_root should be i64. The StateVersion can be set to V0 in ext_storage_root_version_2, which implies that the node in the Merkle tree are full values of arbitrary size and hence need i64 as return type.

**Comment by lamafab** [comment]
I'm not sure this is correct. The version 1 uses `i64` because the size of the hashes can be different _in substrate_ (implementation specific, that was not our decision). Regarding version two, <del>where the hash is fixed, the return value is `i32` and</del> the state version does not influence the size, it's merely a performance change.

But I could be wrong, do tell if this was a mistake.

**Comment by lamafab** [comment]
Actually this might be correct, the return value of version 2 is the same:

```rust
	/// "Commit" all existing operations and compute the resulting storage root.
	///
	/// The hashing algorithm is defined by the `Block`.
	///
	/// Returns a `Vec<u8>` that holds the SCALE encoded hash.
	fn root(&mut self) -> Vec<u8> {
		self.storage_root(StateVersion::V0)
	}

	/// "Commit" all existing operations and compute the resulting storage root.
	///
	/// The hashing algorithm is defined by the `Block`.
	///
	/// Returns a `Vec<u8>` that holds the SCALE encoded hash.
	#[version(2)]
	fn root(&mut self, version: StateVersion) -> Vec<u8> {
		self.storage_root(version)
	}
```

**Comment by bhargavbh** [comment]
exactly, looking at the substrate code, both the versions of storage_root return a `Vec<u8>`. ext_storage_root_version_2 called with argument StateVersion::V0 and ext_storage_root_version_1 are basically identical and must have the same return type.

**Comment by bhargavbh** [comment]
Created a PR with the changed return type. Double checked similar errors for rest of the Host API. 
https://github.com/w3f/polkadot-spec/pull/535
