### ISSUE TITLE
Metadata field name is optional

### ISSUE THREAD

**Issue by tomaka** [w3f/polkadot-spec#539]
In the metadata format, the name of a field is an optional string rather than a string.

https://spec.polkadot.network/#defn-rtm-field

**Comment by FlorianFranzen** [comment]
Right, that is also what the [kaitai table](https://spec.polkadot.network/#metadata_type_fields) says. Thanks!

**Comment by FlorianFranzen** [comment]
Also, if you find anything else related to the metadata, feel free to add it to the review of #517.

**Comment by tomaka** [comment]
The other small issues I've encountered are:

- In "Definition 169. Variant", the definition (`Vi = ...`) is correct, however `c` is missing from the list of definitions underneath, so it's easy to miss.
- In [10.1. Structure](https://spec.polkadot.network/#sect-rtm-structure), the format of `Ve` isn't defined properly in the text.
- In "Definition 167. Type Variant", it doesn't properly say that C, V, and S are sequences. It's kind of obvious, but everywhere else it's written explicitly.

**Comment by lamafab** [comment]
Fixed in #517
