### ISSUE TITLE
Spec Slot-number for given time

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#54]
it seems that the implementation is using an absolute slot number. 
this is not what is specified in Babe research paper and I'm not sure if it is 
compatible with the median approach so this need to be clarified and updated 
in the spec.

**Comment by FlorianFranzen** [comment]
Is replaced by relative time algorithm in #168 and migration will most likely be discussed in w3f/research-security-issues#7.

**Comment by FlorianFranzen** [comment]
I think this is being tracked in enough issues for now, so we can close this.
