### ISSUE TITLE
"Reserved for compact encoding" constant is incorrect

### ISSUE THREAD

**Issue by tomaka** [w3f/polkadot-spec#543]
In the "node header" section (https://spec.polkadot.network/#defn-node-header), "Reserved for compact encoding" is defined as 0001000. In reality it's 00000001.

https://github.com/paritytech/trie/blob/aff1cbac8f03e8dc7533263b374dc0fcd17444ad/test-support/reference-trie/src/substrate_like.rs#L55

**Comment by cheme** [comment]
I confirm.

**Comment by tomaka** [comment]
Note that the text below that talk about distinguishing this value from the other because the other 4 bits are zero doesn't really make sense anymore.
