### ISSUE TITLE
Define authority directory for each epoch

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#55]
We need to spec how to retrieve the authority list at begining of each epoch
This is basically should be contained an algorithm which need to be called
at the begining of each epoch for babe. This also need to include how 
to retrieve session key of each authority and how to verify them.

**Comment by FlorianFranzen** [comment]
This closely relates to specifying NextEpochDescriptor` #173.

**Comment by FlorianFranzen** [comment]
> This also need to include how to retrieve session key of each authority and how to verify them.

This is the only thing really missing. @drskalman If you add a bit more details of what you think is missing, I can add this as well.

**Comment by drskalman** [comment]
Currently spec suggests how to update the authorities but if we have a central one algorithm that take care of all setting in and out of authorities, it is very helpful for the implementers.

**Comment by drskalman** [comment]
This needs to be waited till pull request #168 to be merged first.

**Comment by FlorianFranzen** [comment]
@lamafab Will track the remaining work in #121.
