### ISSUE TITLE
Remove "to_block" field from BlockRequests

### ISSUE THREAD

**Issue by tomaka** [w3f/polkadot-spec#553]
Concerns [section](https://spec.polkadot.network/#sect-msg-block-request)

In https://github.com/paritytech/substrate/pull/12447, we're removing the `to_block` field from block requests (the one which has a formatting issue in the spec right now).
This field is totally ignored by Substrate when answering requests, and never gets set except for one specific situation where we request only one block.

**Comment by lamafab** [comment]
Fixed in #556
