### ISSUE TITLE
Remove mention of "mplex" from the networking

### ISSUE THREAD

**Issue by tomaka** [w3f/polkadot-spec#570]
The `mplex` protocol really shouldn't be used. It's really bad. We continued supporting it in Substrate because there's `js-libp2p-yamux` library, but any new implementation of the host shouldn't implement `mplex`.

(I wanted to straight-up open a PR, but it seems that GitHub is having issues preventing me from pushing/pulling branches)

**Comment by FlorianFranzen** [comment]
Sounds fair. Does JS also support other protocols multiplexers or does that mean we actual drop support for some older clients?

**Comment by tomaka** [comment]
We're talking about an attempt at a JS client abandoned 3/4 years ago, so I'd lean for no.
