### ISSUE TITLE
Light Client Spec: intro

### ISSUE THREAD

**Issue by bhargavbh** [w3f/polkadot-spec#581]
Add light client spec in the intro: brief mention of objectives of a light client; include high-level functional, efficiency and security requirements of the client.
https://github.com/w3f/polkadot-spec/tree/bnb/light-client

**Comment by bkchr** [comment]
The spec should not mention most of the stuff. The spec should specify the light client protocol and that's it. If you want to describe how a light client works, that should be done outside of the spec, because this isn't the job of the spec.

**Comment by bhargavbh** [comment]
Agreed. Will keep the intro bare minimum just to get the definitions going, with focus on requirements.

**Comment by bhargavbh** [comment]
addressed here. 
https://github.com/w3f/polkadot-spec/pull/597
https://github.com/w3f/polkadot-spec/pull/607
Creating a separate tracking issue for future additions to light client chapters
