### ISSUE TITLE
networking: clean up genesis hash in protocol ids

### ISSUE THREAD

**Issue by FlorianFranzen** [w3f/polkadot-spec#586]
We probably should not use actual genesis hashes in the spec but placeholders instead.

**Comment by bhargavbh** [comment]
the following issues argue why genesis hash is preferred over protocolID for naming network streams https://github.com/paritytech/substrate/issues/7252 , https://github.com/paritytech/substrate/issues/7746. The spec currently has the _genesis hash_ versions and a note that protocolID are also valid substreams. I would leave it as it is for the sake simplicity. Please let us know if there is a compelling reason to have placeholders.
