### ISSUE TITLE
Spec ext-network-state return value

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#60]
This requires a deeper look since it includes datastructures from libp2p-dev.

  You would need to call into libp2pThe local PeerId should be know, as well as the Multiaddress you are being reachable from the outside. You take these values and call PeerId.encode(), MultiAddress.iter().map(Encode::encode() And this stuff is put inot the OpaqueNetworkState. It is opaque, because it only has Vec<u8> and does not know of the actual structure of the types. But libp2p knows how these types look like.
````
pub struct OpaqueNetworkState {
	/// PeerId of the local node.
	pub peer_id: OpaquePeerId,
	/// List of addresses the node knows it can be reached as.
	pub external_addresses: Vec<OpaqueMultiaddr>,
}
````

**Comment by lamafab** [comment]
Done in #66
