### ISSUE TITLE
Improve pdf rendering

### ISSUE THREAD

**Issue by davxy** [w3f/polkadot-spec#600]
Looks like formulas and code snips are not rendered correctly by the pdf reader.

Probably the issue affects the overall document, but I report just some examples

---

Definition 60. Winning Threshold 

No newline at the end of each formula (Aw and Tε)

![image](https://user-images.githubusercontent.com/8143589/210344035-662e77a9-4c21-4d3d-8cc2-758475df66cd.png)

---

Algorithm 9 - Invoke-Block-Authoring

Not very readable

![image](https://user-images.githubusercontent.com/8143589/210344061-3228c8fe-1fe3-4792-af16-89ef225060f3.png)

---

Algorithm 10 - Verify-Authorship-Right

Almost unreadable (maybe monospace should be used?)

![image](https://user-images.githubusercontent.com/8143589/210344088-f51425f1-2ba5-46ba-a7ad-45100537ccd7.png)

---

Definition 62. BABE Slot VRF transcript

No newlines between each formula, at the moment is not very readable

![image](https://user-images.githubusercontent.com/8143589/210371608-6dbfe312-e8e9-4194-bb23-7094f81083a3.png)

---

The issue seems not related to the particular pdf reader application.

**Comment by bhargavbh** [comment]
We have migrated the spec to docusaurus and are not maintaining the PDF versions anymore. Let us know if PDF version is of particular interest for you, we will try to support

**Comment by bhargavbh** [comment]
Closing the issue, please comment if it needs to be reopened.
