### ISSUE TITLE
Details about the SCALE Result value encoding

### ISSUE THREAD

**Issue by radkomih** [w3f/polkadot-spec#602]
While reading the [Substrate docs](https://docs.substrate.i/reference/scale-codec/) I found this:
```
Results are encoded as:
    0x00 if the operation was successful, followed by the encoded value.
    0x01 if the operation was unsuccessful, followed by the encoded error.
``` 
which is not mentioned in the spec. There is something similar for the Option type, but I think since they are different types it should be described for the Result too.

**Comment by lamafab** [comment]
So our _Result_ type is defined as:

> The Result type is a varying data type ...

And _varying data type_ is defined as: https://spec.polkadot.network/#defn-varrying-data-type with a direct reference to _Option_ and _Result_:

> In particular, we define two specific varying data which are frequently used in various part of Polkadot protocol: Option ([Definition 190](https://spec.polkadot.network/#defn-option-type)) and Result ([Definition 191](https://spec.polkadot.network/#defn-result-type)).
