### ISSUE TITLE
Outdated Runtime API spec

### ISSUE THREAD

**Issue by failfmi** [w3f/polkadot-spec#604]
Based on the latest release of Polkadot [0.9.37](https://github.com/paritytech/polkadot/releases/tag/v0.9.37) as of **now**, here are the differences between runtime and spec:

* [ ] [BlockBuilder_random_seed](https://spec.polkadot.network/#id-blockbuilder_random_seed) - no longer found in runtime
* [ ] `NominationPoolsApi_pending_rewards` - missing in spec
* [ ] `ParachainHost_validation_code_hash` - missing in spec
* [ ] `ParachainHost_assumed_validation_data` - missing in spec
* [ ] `ParachainHost_on_chain_votes` - missing in spec
* [ ] `ParachainHost_submit_pvf_check_statement` - missing in spec
* [ ] `ParachainHost_pvfs_require_precheck` - missing in spec
* [ ] `BeefyApi_validator_set` - missing in spec
* [ ] `MmrApi_mmr_root` - missing in spec
* [ ] `MmrApi_mmr_leaf_count` - missing in spec
* [ ] `MmrApi_generate_proof` - missing in spec
* [ ] `MmrApi_verify_proof`- missing in spec
* [ ] `MmrApi_verify_proof_stateless` - missing in spec
* [ ] `GrandpaApi_current_set_id` - missing in spec
* [ ] `TransactionPaymentCallApi_query_call_info` - missing in spec
* [ ] `TransactionPaymentCallApi_query_call_fee_details` - missing in spec

**Comment by bhargavbh** [comment]
migrated to new spec format here https://github.com/w3f/polkadot-spec/pull/643. Further TODOs regarding runtime API have been listed in a new tracking issue https://github.com/w3f/polkadot-spec/issues/645
