### ISSUE TITLE
Runtime formatting modules

### ISSUE THREAD

**Issue by failfmi** [w3f/polkadot-spec#605]
There are a few runtime modules that are nested in another modules:
* [ ] [Module AuthorityDiscoveryApi](https://spec.polkadot.network/#id-module-authoritydiscoveryapi) - should not be nested inside of BabeApi
* [ ] [Module SessionKeys](https://spec.polkadot.network/#sect-runtime-sessionkeys-module) - should not be nested inside of BabeApi
* [ ] [Module TransactionPaymentApi](https://spec.polkadot.network/#id-module-transactionpaymentapi) - should not be nested inside of AccountNonceApi

**Comment by bhargavbh** [comment]
migrated to new spec format here https://github.com/w3f/polkadot-spec/pull/643. Further TODOs regarding runtime API have been listed in a new tracking issue https://github.com/w3f/polkadot-spec/issues/645
