### ISSUE TITLE
update: `inherent data` missing important inherent keys

### ISSUE THREAD

**Issue by EclesioMeloJunior** [w3f/polkadot-spec#609]
### Description

Currently, the Polkadot Specification the `inherent data` table  (https://spec.polkadot.network/#tabl-inherent-data) is missing important inherent keys such as:

- `babeslot`
- `uncles00`
- `parachn0`
- `newheads`

**Comment by EclesioMeloJunior** [comment]
If it's not a problem, I can start updating the table.

**Comment by bkchr** [comment]
> * uncles00

This was never used and isn't required.

> * babeslot

We also don't use this anymore, but is maybe required for some old blocks.

>     * `newheads`

Not sure what inherent this is.
