### ISSUE TITLE
using Authority Set ID and Authority List interchangeably is incorrect

### ISSUE THREAD

**Issue by bhargavbh** [w3f/polkadot-spec#611]
The spec seems to be confusing [Authority Set ID](https://spec.polkadot.network/#defn-authority-set-id) and [Authority List](https://spec.polkadot.network/#defn-authority-list). For example, [definition-44](https://spec.polkadot.network/#defn-grandpa-vote-msg) talks about id_V, authority set ID, but links to Authority list. 
The following components are affected:
- https://spec.polkadot.network/#defn-grandpa-vote-msg
- https://spec.polkadot.network/#defn-grandpa-commit-msg
- https://spec.polkadot.network/#defn-sign-round-vote
- https://spec.polkadot.network/#net-msg-approval-distribution
- https://spec.polkadot.network/#algo-process-catchup-request
- https://spec.polkadot.network/#sect-rt-api-validator-groups
- https://spec.polkadot.network/#sect-rt-api-session-info

**Comment by Noc2** [comment]
Thanks!
