### ISSUE TITLE
Three host functions used by the runtime and not in the specs

### ISSUE THREAD

**Issue by tomaka** [w3f/polkadot-spec#614]
The three following host functions are imported by the Polkadot/Westend runtimes, but aren't documented on https://spec.polkadot.network/:

- ext_offchain_index_set_version_1
- ext_offchain_index_clear_version_1
- ext_logging_max_level_version_1

**Comment by bhargavbh** [comment]
addressed in the [PR-642](https://github.com/w3f/polkadot-spec/pull/642)
