### ISSUE TITLE
Research current state of old and new JSON RPC interface in relation to PSP.

### ISSUE THREAD

**Issue by FlorianFranzen** [w3f/polkadot-spec#627]
The following calls are documented buy not implemented:
- archive_unstable_body
- archive_unstable_genesisHash
- archive_unstable_hashByHeight
- archive_unstable_header
- archive_unstable_stopBody
- archive_unstable_stopHashByHeight
- archive_unstable_stopHeader
- archive_unstable_stopStorage
- archive_unstable_storage
- babe_epochAuthorship
- chainSpec_unstable_chainName
- chainSpec_unstable_genesisHash
- chainSpec_unstable_properties
- contracts_call
- contracts_getStorage
- contracts_rentProjection
- engine_createBlock
- engine_finalizeBlock
- rpc_methods
- sudo_sessionKeys_unstable_generate
- sudo_unstable_p2pDiscover
- sudo_unstable_pendingTransactions
- sudo_unstable_version
- system_networkState

The following are implemented but not documented:
- account_nextIndex
- beefy_getFinalizedHead
- beefy_subscribeJustifications
- beefy_unsubscribeJustifications
- chain_getFinalisedHead
- chain_getHead
- chain_getRuntimeVersion
- chain_subscribeFinalisedHeads
- chain_subscribeNewHead
- chain_subscribeRuntimeVersion
- chain_unsubscribeFinalisedHeads
- chain_unsubscribeNewHead
- chain_unsubscribeRuntimeVersion
- childstate_getKeysPaged
- childstate_getKeysPagedAt
- childstate_getStorageEntries
 -mmr_generateProof
- mmr_root
- mmr_verifyProof
- mmr_verifyProofStateless
- payment_queryFeeDetails
- state_callAt
- state_getChildReadProof
- state_getKeys
- state_getKeysPagedAt
- state_getStorageAt
- state_getStorageHashAt
- state_getStorageSizeAt
- state_queryStorageAt
- state_traceBlock
- state_trieMigrationStatus
- subscribe_newHead
- system_addLogFilter
- system_dryRunAt
- system_reservedPeers
- system_resetLogFilter
- system_unstable_networkState
- unsubscribe_newHead

**Comment by bkchr** [comment]
RPC should not be part of the core spec.

**Comment by Noc2** [comment]
Thanks a lot, @FlorianFranzen.  This is about https://github.com/w3f/PSPs/blob/master/PSPs/drafts/psp-6.md @lamafab can take a look at it and we will discuss it.
