### ISSUE TITLE
Schnorrkel spec

### ISSUE THREAD

**Issue by keorn** [w3f/polkadot-spec#63]

**Comment by burdges** [comment]
[Ristretto](https://ristretto.group/) has an [IRTF draft](https://tools.ietf.org/html/draft-hdevalence-cfrg-ristretto-01).  See [cfrg discussions](https://mailarchive.ietf.org/arch/browse/cfrg/?gbt=1&q=ristretto).  

Anytime I first cite Ristretto in a document I single out section 7 of Mike Hamberg's [Decaf](https://www.shiftleft.org/papers/decaf/) paper too.  Ristretto implements section 7 with minor changes, but only credits Decaf for the big picture, but never credits section 7 specifically.  

We'll presumably refer to [merlin's specification](https://merlin.cool/), which itself is specified in terms of [STROBE's specification](https://strobe.sourceforge.io/specs/).  We could do this via my [`SigningTranscript` abstraction](https://github.com/w3f/schnorrkel/blob/master/src/context.rs), although maybe conflating the randomness provisions with the hashing detracts from the document.

**Comment by lamafab** [comment]
We expanded the VRF section in #480, including the low-level operations (merlin/STROBE).
