### ISSUE TITLE
Document that runtimes can be zstd-compressed

### ISSUE THREAD

**Issue by tomaka** [w3f/polkadot-spec#637]
If the runtime binary code starts with a certain prefix, then it is actually zstd-compressed.

The prefix can be found here: https://github.com/paritytech/substrate/blob/f9d10fabe04d598d68f8b097cc4905adbb1ad630/primitives/maybe-compressed-blob/src/lib.rs#L30

The decompressed size has a maximum that can be found here: https://github.com/paritytech/substrate/blob/f9d10fabe04d598d68f8b097cc4905adbb1ad630/primitives/maybe-compressed-blob/src/lib.rs#L37

**Comment by bhargavbh** [comment]
addressed in https://github.com/w3f/polkadot-spec/pull/644.
