### ISSUE TITLE
Authority-discovery mechanism isn't documented

### ISSUE THREAD

**Issue by tomaka** [w3f/polkadot-spec#650]
All the validators of a chain have to publish on the Kademlia DHT a signed record containing their PeerId and addresses at which they are reachable at a key corresponding to their validator key.

The precise format is somewhere here: https://github.com/paritytech/substrate/tree/master/client/authority-discovery

Note that IMO we shouldn't put the name "authority discovery" in the spec, instead we should just mention that validators have to publish a record in the DHT without giving a name to that mechanism.

**Comment by heversonbr** [comment]
Topic added by [PR669](https://github.com/w3f/polkadot-spec/pull/669).
