### ISSUE TITLE
Scrap the sections about BEEFY

### ISSUE THREAD

**Issue by tomaka** [w3f/polkadot-spec#657]
As the text says, these sections describe an early draft. Everything has vastly changed here. If someone was actively maintaining an up-to-date version of what the people working on BEEFY were doing, it could arguably not be a bad thing to have these sections. But that's not the case.

https://spec.polkadot.network/chap-networking#sect-msg-grandpa-beefy
https://spec.polkadot.network/sect-finality#sect-grandpa-beefy

**Comment by bhargavbh** [comment]
We have prioritised rewriting the BEEFY spec, which we plan to finish in the upcoming month. We have a feature branch for this topic https://github.com/w3f/polkadot-spec/tree/bnb/beefy-spec. Also created an issue to track the progress https://github.com/w3f/polkadot-spec/issues/670.
Closing this issue, further discussions on BEEFY can be continued in the new issue.

**Comment by tomaka** [comment]
The point of this issue is precisely to remove the current spec, which everyone agrees is obsolete, in order to avoid confusion.

I understand and I'm grateful that you're going to improve the spec in the upcoming months, but this issue isn't about having an accurate BEEFY specification but about making the inaccurate one disappear.

**Comment by bhargavbh** [comment]
Fair enough. https://github.com/w3f/polkadot-spec/pull/673 the stubs have been removed
