### ISSUE TITLE
Beefy Light client is not supposed to have access to the public keys of the validators 

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#658]
@AlistairStewart noticed this line in the spec of light client:

The light client is expected to know who the validators are and has access to their public keys.

This is not how BEEFY light client supposed to work. It does have access to the a commitment to the set of validator publickeys which is not mentioned in the spec and should be mentioned. In contrast in both ECDSA and APK proof BEEFY it does not have immediate access to the public keys so the statement is not correct.

**Comment by bhargavbh** [comment]
Just confirming if you are referring to 6.7.1 (https://spec.polkadot.network/sect-finality#defn-beefy-light-client) and not in the light client chapter. Further, I would also suggest changing the name in definition from 'Light Client' to 'Beefy Light Client'.

**Comment by bhargavbh** [comment]
addressed in Beefy PR here https://github.com/w3f/polkadot-spec/pull/682
