### ISSUE TITLE
Write a first step basic network integration test

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#69]
Basically:
1. running a substarte client, running a gosammar client such that your substrate node (probably with Alexander runtime) is a peer of gosammar client.

2. receive the gosammer status message and check if it is complying with spec (if substrate client doesn't drop them as peer then probably they are).

3. send a blockrequest message and see if they reply according to spec.

**Comment by lamafab** [comment]
Upstream libp2p changes are currently being worked on (also adapting the new async/await Rust syntax). I will work on this one those changes are completed.

**Comment by lamafab** [comment]
-> doing something new with Ximin
