### ISSUE TITLE
Controller accounts are being deprecated

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-spec#692]
I noticed several references and details to Controller accounts (e.g. https://spec.polkadot.network/id-cryptography-encoding ). Note that these are in the process of being deprecated ( https://forum.polkadot.network/t/staking-controller-deprecation-plan-staking-ui-leads-comms/2748 ) and these will need to be removed.

**Comment by heversonbr** [comment]
Fixed on Controller keys deprecation [#700](https://github.com/w3f/polkadot-spec/pull/700)
