### ISSUE TITLE
BABE clock - space for examples, but none given 

### ISSUE THREAD

**Issue by laboon** [w3f/polkadot-spec#694]
Page: https://spec.polkadot.network/sect-block-production

"Polkadot does this synchronization without relying on any external clock source (e.g., through the or the )."

There are just blank spaces after the two "the"'s - I assume there should be examples that go there. Otherwise the parenthetical clause can be removed.

**Comment by bhargavbh** [comment]
Thanks Bill! https://github.com/w3f/polkadot-spec/pull/696 closes the issue
