### ISSUE TITLE
Fix the rust code so it works with the new executor api

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#70]
- There have been some big changes in the Substrate codebase; is it no longer possible to use call_with_custom_signature (since WasmExecutor has been changed to WasmRuntime)?
are the specced requirements now obligatory?

- The signature is still the same

- How about custom ones?

- https://github.com/paritytech/substrate/blob/master/core/executor/runtime-test/src/lib.rs#L17 you could adapt this macro for your tests

**Comment by lamafab** [comment]
Fixed in the "lamafab-pdre-tests" branch. Merged directly into master, no PR opened.
