### ISSUE TITLE
Hard-coded website spec version regardless of new deployments/tags/releases

### ISSUE THREAD

**Issue by failfmi** [w3f/polkadot-spec#708]
Regardless of new deployments (e.g. `v0.3.1`), whenever you open https://spec.polkadot.network/ it show the version is `v0.2.1`. The hard-coded value is [here](https://github.com/w3f/polkadot-spec-website/blob/main/docusaurus.config.js#L15).

**Comment by heversonbr** [comment]
Fixed by [PR#4](https://github.com/w3f/polkadot-spec-website/pull/4)

**Comment by heversonbr** [comment]
Fixed by [PR#4](https://github.com/w3f/polkadot-spec-website/pull/4)
