### ISSUE TITLE
Repeated imported function

### ISSUE THREAD

**Issue by neithanmo** [w3f/polkadot-spec#712]
In the host-api documentation, the section [Offchain_index_clear](https://spec.polkadot.network/chap-host-api#id-offchain_index_set)  describes a function that is used to clear the storage, however, in the code snippet it has the same name as the function described in the previous section:
- Offchain_index_set(section)
```
(func $ext_offchain_index_set_version_1
    (param $key i64) (param $value i64))
```

- Offchain_index_clear(section)
```
(func $ext_offchain_index_set_version_1
    (param $key i64)) 
```
I think the method should be renamed to `ext_offchain_index_clear_version_1
`

**Comment by bhargavbh** [comment]
Thanks for pointing out,
it has been fixed here https://github.com/w3f/polkadot-spec/pull/713
