### ISSUE TITLE
Spec suggests using wrong substream for fetching state information

### ISSUE THREAD

**Issue by vikinatora** [w3f/polkadot-spec#723]
In the spec, it's said that `/sync/2` is used for block requsests and state requests. However, that substream is only good for fetching block information. We tried countless ways of sending a state request but the response just didn't arrive. After lots of hours spent trying to find out why state requests don't work, we stumbled upon Kagome's [code](https://github.com/qdrvm/kagome/blob/7ddfc1e0d42f3df85657ced3fa0b00e769aa6aad/core/network/common.hpp#L21), where we found out there's another undocumented substream `/state/2` that's used for making state requests. 

We suggest adding this substream to the spec because it's not documented and changing the existing spec to point to the new substream for state requests.

**Comment by bhargavbh** [comment]
hi @vikinatora thanks for bringing this to our attention. We will look into it ASAP.

**Comment by bhargavbh** [comment]
adressed in PR https://github.com/w3f/polkadot-spec/pull/724
